/* eslint-disable prefer-arrow-callback,prefer-template */
Package.describe({
  name:          'tunguska:meteor-testing',
  version:       '1.0.0',
  summary:       'A test runner to enable easy testing with meteor',
  git:           'https://github.com/robfallows/tunguska-meteor-testing.git',
  documentation: 'README.md',
  testOnly:      true,
});

Package.onUse(function onUse(api) {

  api.versionsFrom('1.3.5.1');

  /**
   * Dependencies
   */
  api.use('ecmascript');
  api.use('accounts-base',             [ 'server', 'client' ]);
  api.use('http',                      [ 'server' ]);
  api.use('underscore',                [ 'client', 'server' ]);
  api.use('service-configuration',     [ 'client', 'server' ]);
  api.use('tunguska:mocha-core@1.0.0', [ 'client', 'server' ]);

  /**
   * 1. exec `find . -type f` within the slimer folder to create a list of files
   * 2. addAssets to  the list of files.
   *
   * Note: All the files are needed! @TODO: check this assertion!
   * @type {Array}
   */
  ['LICENSE',
    'slimerjs.bat',
    'chrome/branding/content/icon64.png',
    'chrome/branding/content/about.png',
    'chrome/branding/content/icon48.png',
    'chrome/branding/locale/brand.properties',
    'chrome/branding/locale/brand.dtd',
    'chrome/icons/default/default32.png',
    'chrome/icons/default/slimerjswin.ico',
    'chrome/icons/default/default48.png',
    'chrome/slimerjs/content/slimerjs.xul',
    'chrome/slimerjs/content/webpage.xul',
    'chrome/slimerjs/content/slimerjs.js',
    'chrome/slimerjs/content/slimerjs.png',
    'chrome/slimerjs/content/webpage.js',
    'chrome/slimerjs/content/slimerjs.css',
    'chrome/slimerjs/locale/en-US/slimerjs.dtd',
    'package_exclude.lst',
    'macos/Info.plist',
    'defaults/preferences/prefs.js',
    'defaults/preferences/debug.js',
    'phantom-protocol.js',
    'slimerjs',
    'chrome.manifest',
    'slimerjs.py',
    'vendors/ghostdriver/main.js',
    'vendors/ghostdriver/webelementlocator.js',
    'vendors/ghostdriver/inputs.js',
    'vendors/ghostdriver/webdriver_atoms.js',
    'vendors/ghostdriver/errors.js',
    'vendors/ghostdriver/logger.js',
    'vendors/ghostdriver/config.js',
    'vendors/ghostdriver/request_handlers/session_manager_request_handler.js',
    'vendors/ghostdriver/request_handlers/status_request_handler.js',
    'vendors/ghostdriver/request_handlers/shutdown_request_handler.js',
    'vendors/ghostdriver/request_handlers/request_handler.js',
    'vendors/ghostdriver/request_handlers/router_request_handler.js',
    'vendors/ghostdriver/request_handlers/session_request_handler.js',
    'vendors/ghostdriver/request_handlers/webelement_request_handler.js',
    'vendors/ghostdriver/ghostdriver.qrc',
    'vendors/ghostdriver/hub_register.js',
    'vendors/ghostdriver/session.js',
    'vendors/ghostdriver/lastupdate',
    'vendors/ghostdriver/README.md',
    'vendors/ghostdriver/third_party/uuid.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/tap.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/get_window_position.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/get_location.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/rotate.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/set_window_position.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/swipe.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/find_elements.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/get_local_storage_item.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/get_attribute_value.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/find_element.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/clear.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/drag.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/focus_on_element.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/is_enabled.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/default_content.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/submit.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/execute_script.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/get_in_view_location.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/deps.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/right_click.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/get_frame_window.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/get_top_left_coordinates.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/get_current_position.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/frame_by_index.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/remove_session_storage_item.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/execute_async_script.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/get_local_storage_size.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/move_mouse.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/frame_by_id_or_name.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/get_session_storage_keys.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/pinch.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/get_element_from_cache.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/remove_local_storage_item.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/execute_sql.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/active_element.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/set_session_storage_item.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/is_selected.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/clear_session_storage.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/get_value_of_css_property.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/get_local_storage_keys.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/set_local_storage_item.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/is_displayed.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/set_window_size.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/get_session_storage_item.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/type.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/scroll_mouse.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/get_size.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/lastupdate',
    'vendors/ghostdriver/third_party/webdriver-atoms/double_click.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/clear_local_storage.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/get_attribute.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/get_text.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/get_location_in_view.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/scroll_into_view.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/get_window_size.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/click.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/get_session_storage_size.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/get_appcache_status.js',
    'vendors/ghostdriver/third_party/webdriver-atoms/is_online.js',
    'vendors/ghostdriver/third_party/har.js',
    'vendors/ghostdriver/third_party/console++.js',
    'vendors/ghostdriver/third_party/parseuri.js',
    'modules/addon-sdk/toolkit/loader.js',
    'modules/addon-sdk/sdk/net/url.js',
    'modules/addon-sdk/sdk/net/xhr.js',
    'modules/addon-sdk/sdk/selection.js',
    'modules/addon-sdk/sdk/url.js',
    'modules/addon-sdk/sdk/util/collection.js',
    'modules/addon-sdk/sdk/util/object.js',
    'modules/addon-sdk/sdk/util/uuid.js',
    'modules/addon-sdk/sdk/util/list.js',
    'modules/addon-sdk/sdk/util/registry.js',
    'modules/addon-sdk/sdk/util/array.js',
    'modules/addon-sdk/sdk/util/deprecate.js',
    'modules/addon-sdk/sdk/io/file.js',
    'modules/addon-sdk/sdk/io/byte-streams.js',
    'modules/addon-sdk/sdk/io/text-streams.js',
    'modules/addon-sdk/sdk/system.js',
    'modules/addon-sdk/sdk/deprecated/traits.js',
    'modules/addon-sdk/sdk/deprecated/window-utils.js',
    'modules/addon-sdk/sdk/deprecated/events/assembler.js',
    'modules/addon-sdk/sdk/deprecated/observer-service.js',
    'modules/addon-sdk/sdk/deprecated/unit-test-finder.js',
    'modules/addon-sdk/sdk/deprecated/list.js',
    'modules/addon-sdk/sdk/deprecated/errors.js',
    'modules/addon-sdk/sdk/deprecated/api-utils.js',
    'modules/addon-sdk/sdk/deprecated/traits/core.js',
    'modules/addon-sdk/sdk/deprecated/memory.js',
    'modules/addon-sdk/sdk/deprecated/cortex.js',
    'modules/addon-sdk/sdk/deprecated/light-traits.js',
    'modules/addon-sdk/sdk/deprecated/events.js',
    'modules/addon-sdk/sdk/deprecated/tab-browser.js',
    'modules/addon-sdk/sdk/deprecated/unit-test.js',
    'modules/addon-sdk/sdk/deprecated/app-strings.js',
    'modules/addon-sdk/sdk/notifications.js',
    'modules/addon-sdk/sdk/clipboard.js',
    'modules/addon-sdk/sdk/system/unload.js',
    'modules/addon-sdk/sdk/system/xul-app.js',
    'modules/addon-sdk/sdk/system/events.js',
    'modules/addon-sdk/sdk/system/environment.js',
    'modules/addon-sdk/sdk/system/runtime.js',
    'modules/addon-sdk/sdk/system/globals.js',
    'modules/addon-sdk/sdk/querystring.js',
    'modules/addon-sdk/sdk/core/promise.js',
    'modules/addon-sdk/sdk/core/heritage.js',
    'modules/addon-sdk/sdk/core/disposable.js',
    'modules/addon-sdk/sdk/core/namespace.js',
    'modules/addon-sdk/sdk/timers.js',
    'modules/addon-sdk/sdk/base64.js',
    'modules/addon-sdk/sdk/self.js',
    'modules/addon-sdk/sdk/platform/xpcom.js',
    'modules/addon-sdk/xul-app.jsm',
    'modules/slLauncher.jsm',
    'modules/slConfiguration.jsm',
    'modules/hello/people.js',
    'modules/hello/world.js',
    'modules/slPhantomJSKeyCode.jsm',
    'modules/webpageUtils.jsm',
    'modules/slQTKeyCodeToDOMCode.jsm',
    'modules/slConsole.jsm',
    'modules/slUtils.jsm',
    'modules/slDebug.jsm',
    'modules/coffee-script/LICENSE',
    'modules/coffee-script/README',
    'modules/coffee-script/lib/coffee-script/repl.js',
    'modules/coffee-script/lib/coffee-script/nodes.js',
    'modules/coffee-script/lib/coffee-script/parser.js',
    'modules/coffee-script/lib/coffee-script/browser.js',
    'modules/coffee-script/lib/coffee-script/cake.js',
    'modules/coffee-script/lib/coffee-script/grammar.js',
    'modules/coffee-script/lib/coffee-script/coffee-script.js',
    'modules/coffee-script/lib/coffee-script/rewriter.js',
    'modules/coffee-script/lib/coffee-script/lexer.js',
    'modules/coffee-script/lib/coffee-script/command.js',
    'modules/coffee-script/lib/coffee-script/optparse.js',
    'modules/coffee-script/lib/coffee-script/scope.js',
    'modules/coffee-script/lib/coffee-script/index.js',
    'modules/coffee-script/lib/coffee-script/helpers.js',
    'modules/coffee-script/package.json',
    'modules/coffee-script/extras/coffee-script.js',
    'modules/slErrorLogger.jsm',
    'modules/slExit.jsm',
    'modules/slCookiesManager.jsm',
    'modules/slimer-sdk/vm.js',
    'modules/slimer-sdk/bootstrap.js',
    'modules/slimer-sdk/system.js',
    'modules/slimer-sdk/webserver.jsm',
    'modules/slimer-sdk/phantom.jsm',
    'modules/slimer-sdk/webpage.js',
    'modules/slimer-sdk/slimer.jsm',
    'modules/slimer-sdk/net-log.js',
    'modules/slimer-sdk/path.js',
    'modules/httpUtils.jsm',
    'components/SiteSpecificUserAgent.js',
    'components/ConsoleAPI.js',
    'components/DisableAddonManager.js',
    'components/nsPrompter.js',
    'components/helperAppDialog.js',
    'components/SiteSpecificUserAgent.manifest',
    'components/filePicker.js',
    'components/DisabledTelemetryStartup.js',
    'components/httpd.js',
    'components/commandline.js',
    'components/callPhantom.js',
    'components/httpd.xpt',
    'components/navigation.js',
    'components/httpd.manifest',
    'IMPLEMENTATION_DOC.md',
    'README.md',
    'application.ini',
    'slimerjs-node'].forEach(function cb(R) {
    api.addAssets('slimer/slimerjs/' + R, [ 'server' ]);
  });


  /**
   * Assets
   */
  api.addAssets('server/slimer.js', 'server');

  /**
   * Client side
   */
  api.mainModule('client/runner.js', 'client');

  /**
   * Server Side
   */
  api.mainModule('server/runner.js', 'server');

});

Package.onTest(function onTest(api) {

  api.use('ecmascript');
  api.use('tinytest');
  api.use('tunguska:meteor-testing');

});
